
language: perl
perl:
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"


before_install:

  - sudo apt-get update  -qq
  - # sudo apt-get install -qq 
  - cpanm --quiet --notest Template
  - cpanm --quiet --notest JSON::XS HTML::TreeBuilder::XPath

install: ""

script: 
  - hostname
  - pwd
  - echo "=================================================="
  - cd squids; prove -v -Iperl/ t/
